# Form implementation generated from reading ui file 'C:\Users\Maks\PycharmProjects\PythonProject4\admin.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Admin_Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(618, 474)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(210, 10, 221, 51))
        self.label.setStyleSheet('font: 75 28pt "Rubik";')
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(parent=Form)
        self.tableWidget.setGeometry(QtCore.QRect(10, 160, 601, 291))
        self.tableWidget.setVerticalScrollBarPolicy(
            QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded
        )
        self.tableWidget.setHorizontalScrollBarPolicy(
            QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff
        )
        self.tableWidget.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents
        )
        self.tableWidget.setGridStyle(QtCore.Qt.PenStyle.DashLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.pushButton_3 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 120, 71, 31))
        self.pushButton_3.setStyleSheet(
            "background-color: #ebbdb9;\n"
            "color: black;\n"
            "font-size: 20px;\n"
            "font-family: Rubik;\n"
            "border-radius: 1px;\n"
            "border: 2px solid #3f3f3f"
        )
        self.pushButton_3.setObjectName("pushButton_3")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(380, 120, 207, 34))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_2.setStyleSheet(
            "background-color: #ebbdb9;\n"
            "color: black;\n"
            "font-size: 20px;\n"
            "font-family: Rubik;\n"
            "border-radius: 1px;\n"
            "border: 2px solid #3f3f3f"
        )
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton.setStyleSheet(
            "background-color: #b06e68;\n"
            "color: white;\n"
            "font-size: 18px;\n"
            "font-family: Rubik;\n"
            "border-radius: 1px;\n"
            "border: 2px solid #3f3f3f"
        )
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "TROPIK - система бронирования"))
        self.label.setText(_translate("Form", "Admin panel"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "user_id"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "cabinet_id"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "res_id"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "date"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "status"))
        self.pushButton_3.setText(_translate("Form", "Выход"))
        self.pushButton_2.setText(_translate("Form", "Отклонить"))
        self.pushButton.setText(_translate("Form", "Одобрить"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Admin_Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
