# Form implementation generated from reading ui file 'C:\Users\Maks\PycharmProjects\PythonProject4\calendar1.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Cal_Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 400)
        Form.setMinimumSize(QtCore.QSize(500, 400))
        Form.setMaximumSize(QtCore.QSize(500, 400))

        self.selected_date = None  # Добавляем атрибуты для хранения значений
        self.selected_para = None

        self.calendarWidget = QtWidgets.QCalendarWidget(parent=Form)
        self.calendarWidget.setGeometry(QtCore.QRect(30, 50, 451, 183))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setStyleSheet("border: 1px dashed #000;\n" "color: black")
        self.calendarWidget.setObjectName("calendarWidget")

        # Обновляем showdata_lineEdit при выборе даты в календаре
        self.calendarWidget.selectionChanged.connect(self.update_date_text)

        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(30, 10, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet('font: 75 20pt "Rubik";')
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(30, 240, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet('font: 75 18pt "Rubik";')
        self.label_2.setObjectName("label_2")
        self.spinBox = QtWidgets.QSpinBox(parent=Form)
        self.spinBox.setGeometry(QtCore.QRect(30, 280, 91, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.spinBox.setFont(font)
        self.spinBox.setStyleSheet("border: 1px solid #000;\n" "border-radius: 2px")
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(7)
        self.spinBox.setObjectName("spinBox")
        self.spinBox.valueChanged.connect(self.update_para_text)
        self.next_pushButton = QtWidgets.QPushButton(parent=Form)
        self.next_pushButton.setGeometry(QtCore.QRect(400, 350, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(-1)
        self.next_pushButton.setFont(font)
        self.next_pushButton.setStyleSheet(
            "background-color: #ebbdb9;\n"
            "color: black;\n"
            "font-size: 20px;\n"
            "font-family: Rubik;\n"
            "border-radius: 1px;\n"
            "border: 2px solid #3f3f3f"
        )
        self.next_pushButton.setObjectName("next_pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setGeometry(QtCore.QRect(20, 350, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(-1)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet(
            "background-color: #ebbdb9;\n"
            "color: black;\n"
            "font-size: 20px;\n"
            "font-family: Rubik;\n"
            "border-radius: 1px;\n"
            "border: 2px solid #3f3f3f"
        )
        self.pushButton_2.setObjectName("pushButton_2")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(130, 280, 228, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.showpara_lineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.showpara_lineEdit.setObjectName("showpara_lineEdit")
        self.showpara_lineEdit.setStyleSheet(
            "border: 1px solid #000;\n" "border-radius: 2px"
        )
        self.showpara_lineEdit.setReadOnly(True)
        self.showpara_lineEdit.setObjectName("showpara_lineEdit")
        self.horizontalLayout.addWidget(self.showpara_lineEdit)
        self.showdata_lineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.showdata_lineEdit.setStyleSheet(
            "border: 1px solid #000;\n" "border-radius: 2px"
        )
        self.showdata_lineEdit.setReadOnly(True)
        self.showdata_lineEdit.setObjectName("showdata_lineEdit")
        self.horizontalLayout.addWidget(self.showdata_lineEdit)

        self.retranslateUi(Form)
        self.pushButton_2.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "TROPIK — система бронирования"))
        self.label.setText(_translate("Form", "Выберите дату:"))
        self.label_2.setText(_translate("Form", "Выберите пару:"))
        self.next_pushButton.setText(_translate("Form", "Далее"))
        self.pushButton_2.setText(_translate("Form", "Выход"))
        self.showpara_lineEdit.setText(_translate("Form", "Пара"))
        self.showdata_lineEdit.setText(_translate("Form", "Дата"))

    # Добавляем метод для обновления текста
    def update_para_text(self, value):
        self.selected_para = value
        self.showpara_lineEdit.setText(str(value))

        # Метод для обновления даты в showdata_lineEdit

    def update_date_text(self):
        self.selected_date = self.calendarWidget.selectedDate()
        self.showdata_lineEdit.setText(
            self.selected_date.toString("dd.MM.yyyy")
        )  # Формат: день.месяц.г


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Cal_Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
