# Form implementation generated from reading ui file 'C:\Users\Maks\PycharmProjects\PythonProject4\profile.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Pro_Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 400)
        Form.setMinimumSize(QtCore.QSize(500, 400))
        Form.setMaximumSize(QtCore.QSize(500, 400))
        self.historycomboBox = QtWidgets.QComboBox(parent=Form)
        self.historycomboBox.setGeometry(QtCore.QRect(20, 140, 211, 22))
        self.historycomboBox.setStyleSheet(
            'font: 75 12pt "Rubik";\n' "border: 1px solid #000;\n" "border-radius: 2px"
        )
        self.historycomboBox.setObjectName("historycomboBox")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet('font: 75 20pt "Rubik";')
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(20, 200, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet('font: 75 20pt "Rubik";')
        self.label_3.setObjectName("label_3")
        self.statuslineEdit = QtWidgets.QLineEdit(parent=Form)
        self.statuslineEdit.setGeometry(QtCore.QRect(20, 240, 251, 61))
        self.statuslineEdit.setStyleSheet('font: 75 20pt "Rubik";')
        self.statuslineEdit.setObjectName("statuslineEdit")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(360, 10, 135, 63))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lastnamelineEdit = QtWidgets.QLineEdit(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lastnamelineEdit.setFont(font)
        self.lastnamelineEdit.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lastnamelineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lastnamelineEdit.setReadOnly(True)
        self.lastnamelineEdit.setObjectName("lastnamelineEdit")
        self.verticalLayout.addWidget(self.lastnamelineEdit)
        self.widget1 = QtWidgets.QWidget(parent=Form)
        self.widget1.setGeometry(QtCore.QRect(220, 360, 272, 30))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget1)
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(-1)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet(
            "background-color: #b06e68;\n"
            "color: white;\n"
            "font-size: 18px;\n"
            "font-family: Rubik;\n"
            "border-radius: 1px;\n"
            "border: 2px solid #3f3f3f"
        )
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.exitpushButton = QtWidgets.QPushButton(parent=self.widget1)
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(-1)
        self.exitpushButton.setFont(font)
        self.exitpushButton.setStyleSheet(
            "background-color: #ebbdb9;\n"
            "color: black;\n"
            "font-size: 20px;\n"
            "font-family: Rubik;\n"
            "border-radius: 1px;\n"
            "border: 2px solid #3f3f3f"
        )
        self.exitpushButton.setObjectName("exitpushButton")
        self.horizontalLayout.addWidget(self.exitpushButton)

        self.retranslateUi(Form)
        self.exitpushButton.clicked.connect(Form.close)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "TROPIK — система бронирования"))
        self.label_2.setText(_translate("Form", "История заявок:"))
        self.label_3.setText(_translate("Form", "Статус последней заявки:"))
        self.label.setText(_translate("Form", "Профиль"))
        self.lastnamelineEdit.setText(_translate("Form", "Username"))
        self.pushButton_2.setText(_translate("Form", "Создать новую заявку"))
        self.exitpushButton.setText(_translate("Form", "Выход"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Pro_Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
