# Form implementation generated from reading ui file 'C:\Users\Maks\PycharmProjects\PythonProject4\reg.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QLineEdit


class Reg_window_Ui(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(328, 427)
        self.layoutWidget = QtWidgets.QWidget(parent=Form)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 310, 189, 70))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton.setStyleSheet(
            "background-color: #b06e68;\n"
            "color: white;\n"
            "font-size: 18px;\n"
            "font-family: Rubik;\n"
            "border-radius: 1px;\n"
            "border: 2px solid #3f3f3f"
        )
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_2.setStyleSheet(
            "background-color: #ebbdb9;\n"
            "color: black;\n"
            "font-size: 20px;\n"
            "font-family: Rubik;\n"
            "border-radius: 1px;\n"
            "border: 2px solid #3f3f3f"
        )
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 250, 221, 31))
        self.lineEdit_2.setEchoMode(QLineEdit.EchoMode.Password)
        self.lineEdit_2.setStyleSheet(
            "border: 2px solid #cc3e31;\n" "border-radius: 7px;"
        )
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.layoutWidget_2 = QtWidgets.QWidget(parent=Form)
        self.layoutWidget_2.setGeometry(QtCore.QRect(50, 60, 241, 71))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget_2)
        self.label.setStyleSheet('font: 75 28pt "Rubik";')
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        self.label_2.setStyleSheet('font: 75 8pt "Rubik";')
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(60, 170, 51, 16))
        self.label_3.setStyleSheet('font: 75 8pt "Rubik";\n' "font-size: 15px;")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setGeometry(QtCore.QRect(60, 190, 221, 31))
        self.lineEdit.setStyleSheet(
            "border: 2px solid #cc3e31;\n" "border-radius: 7px;"
        )
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(60, 230, 61, 16))
        self.label_4.setStyleSheet('font: 75 8pt "Rubik";\n' "font-size: 15px;")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "TROPIK - система бронирования"))
        self.pushButton.setText(_translate("Form", "Зарегистрироваться"))
        self.pushButton_2.setText(_translate("Form", "Войти в аккаунт"))
        self.label.setText(_translate("Form", "Регистрация"))
        self.label_2.setText(_translate("Form", "Пожалуйста, зарегистрируйтесь"))
        self.label_3.setText(_translate("Form", "Логин"))
        self.label_4.setText(_translate("Form", "Пароль"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Reg_window_Ui()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
